### ISSUE TITLE
Provided nix run command fails

### ISSUE THREAD

**Issue by GHOSCHT** [CTU-IIG/carla-simulator.nix#1]
I'm trying to run the CARLA binary with the command provided by the Readme: 
```sh
nix run github:CTU-IIG/carla-simulator.nix#carla-bin_0_9_14
```
However this fails with following output:
```
error: flake 'github:CTU-IIG/carla-simulator.nix' does not provide attribute 'apps.x86_64-linux.carla-bin_0_9_14', 'packages.x86_64-linux.carla-bin_0_9_14', 'legacyPackages.x86_64-linux.carla-bin_0_9_14' or 'carla-bin_0_9_14'
```
Something similar happens with the other command you provided:
```sh
nix profile install github:CTU-IIG/carla-simulator.nix#scenic
```

```
error: flake 'github:CTU-IIG/carla-simulator.nix' does not provide attribute 'packages.x86_64-linux.scenic', 'legacyPackages.x86_64-linux.scenic' or 'scenic'
```

How would you recommend I should run CARLA on Nix? And since I'm still relatively new to Nix/NixOS, could you elaborate how I could install this without `nix profile install` (I'm using flakes for my own NixOS setup if that's important).

Update: It's running now, since I simply extracted the packaging code in /carla-bin into my own .nix files, but still it would be a good idea to have some up-to date instructions in the Readme.

**Comment by wentasah** [comment]
You're right. I've recently changed the attribute names and forgot to update the README. I'm pushing the correction now.

I've also added an example of flake-based NixOS configuration using this flake.

Let me know, if you need more help. Up to now, I was not aware of any other users except my teammates so I didn't pay that much attention to documenting everything.
